stages:
  - lint
  - test

image: "python:3.6.12-buster"

before_script:
  - python -m pip install --upgrade pip
  - cd su-rmf-pipe
  - pip install -r requirements.txt

# Lint with Black
lint_a:
  stage: lint
  script:
    - black --check src

# Test with coverage and pytest
test_a:
  stage: test
  script:
    - apt install libusb-1.0-0
    - coverage run --source="src" --omit="src/test*" -m pytest -sv
    - coverage report