stages:
  - lint
  - test

image: "python:3.6.12-buster"

before_script:
  - python -m pip install --upgrade pip
  - cd su-rmf-pipe
  - pip install -r requirements.txt

# Lint with Black
lint_a:
  stage: lint
  script:
    - cd su-rmf-pipe/src
    - black --check .

# Test with coverage and pytest
test_a:
  stage: test
  script:
    - cd su-rmf-pipe/src
    - coverage run --source=. --omit="test*" -m pytest -sv && coverage report
