stages:
  - lint
  - test

image: "ubuntu:latest"

before_script:
  - apt-get -yq update
  - apt-get -yq install software-properties-common
  - add-apt-repository -y ppa:deadsnakes/ppa
  - apt-get -yq update
  - apt-get -yq install python3.6
  - ln -s /usr/bin/python3 /usr/local/bin/python36
  - ln -s /usr/bin/python /usr/local/bin/python36
  - python -m pip install --upgrade pip
  - cd su-rmf-pipe
  - pip install -r requirements.txt

# Lint with Black
lint_a:
  stage: lint
  script:
    - black --check src

# Test with coverage and pytest
test_a:
  stage: test
  script:
    - coverage run --source="src" --omit="src/test*" -m pytest -sv
    - coverage report