# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python testing

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd su-rmf-pipe
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        cd su-rmf-pipe/src
        coverage run --source=. --omit="test*" -m pytest -sv && coverage report && coverage html
